### ISSUE TITLE
Phonegap build issue with geofence-branch

### ISSUE THREAD

**Issue by asangadev** [Appboy/appboy-cordova-sdk#26]
Hi there,

**We are getting this error with the:**

```
<plugin name="cordova-plugin-appboy" spec="https://github.com/appboy/appboy-cordova-sdk#geofence-branch" />
```

**config.xml**

```
    <preference name="android-minSdkVersion" value="21" />
    <preference name="android-targetSdkVersion" value="23" />
    <preference name="phonegap-version" value="cli-7.1.0" />
```

**error**

```
1 error
:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.685 secs
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/src/com/appboy/cordova/AppboyPlugin.java:112: error: method onRequestPermissionResult(int,String[],int[]) is already defined in class AppboyPlugin
  public void onRequestPermissionResult(int requestCode, String[] permissions, int[] grantResults) throws JSONException {
              ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by asangadev** [comment]
I have fixed this issue by doing this.
```
 @Override
  public void onRequestPermissionResult(int requestCode, String[] permissions, int[] grantResults) throws JSONException  {
    switch (requestCode) {
      case LOCATION_REQUEST_CODE:
        if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
          Log.i(TAG, "Fine location permission granted.");
          AppboyLocationService.requestInitialization(mApplicationContext);
        } else {
          Log.i(TAG, "Fine location permission NOT granted.");
        }
        break;
      default:
        break;
    }

    // Get location permissions, if we need them
    if (cordova.hasPermission(LOCATION_PERMISSION)) {
      AppboyLocationService.requestInitialization(mApplicationContext);
    } else {
      // Request the permission
      cordova.requestPermission(this, LOCATION_REQUEST_CODE, LOCATION_PERMISSION);
    }
  }

//   @Override
//   public void onRequestPermissionResult(int requestCode, String[] permissions, int[] grantResults) throws JSONException {
//     switch (requestCode) {
//       case LOCATION_REQUEST_CODE:
//         if (grantResults[0] == PackageManager.PERMISSION_GRANTED) {
//           Log.i(TAG, "Fine location permission granted.");
//         } else {
//           Log.i(TAG, "Fine location permission NOT granted.");
//         }
//         break;
//       default:
//         break;
//     }
//   }
```

could you please confirm?
